### ISSUE TITLE
snmp v3

### ISSUE THREAD

**Issue by mase1981** [alhazmy13/Synology-NAS-monitoring#10]
First, thank you so much for the incredible solution. 
Second, Not a bug, but wanted to ask. Is there a way to use this with SNMP v3 vs v1/2 with public? 
Thank you so much !

**Comment by mase1981** [comment]
This can be closed. figured out you can by modifying the config file adding the below: 
/etc/telegraf/telegraf.conf

[[inputs.snmp]]
   agents = [  "172.17.0.1" ]
   version = 3
   auth_protocol = "sha"
   auth_password = :XXXXX"
   sec_level = "authPriv"
   priv_protocol = "AES"
   priv_password = "YYYYY"
   sec_name = "ZZZZZ"
   
   And modifying the NAS v3 configs to match.

**Comment by alhazmy13** [comment]
Sorry for the late reply. You are right; you can change the `/etc/telegraf/telegraf.conf` with your mentioned configs
