### ISSUE TITLE
After last update unable to pull information

### ISSUE THREAD

**Issue by mase1981** [alhazmy13/Synology-NAS-monitoring#12]
Post upgrade to latest container where grafana was updates i am unable to get into influxDB.
Getting the below error when going to configuration and testing connection,

Get "http://localhost:8086/query?db=telegraf&epoch=ms&q=SHOW+measurements": dial tcp 127.0.0.1:8086: connect: connection refused error performing influxQL query

Here is a screenshot of what I see: 
![image](https://user-images.githubusercontent.com/3089864/207463412-2cec0f95-2070-490f-a039-5bcdd9f8f545.png)

**Comment by alhazmy13** [comment]
Dear @mase1981 , thanks for reporting this; I'm working on it right now and ill update you ASAP

**Comment by alhazmy13** [comment]
Dear @mase1981 

Can you test the latest image? It should be fixed now.

Thanks

**Comment by mase1981** [comment]
Issue is now resolved. thank you so much !
