### ISSUE TITLE
docker-compose port 5144:514 needs /udp appending

### ISSUE THREAD

**Issue by RainmakerRaw** [alhazmy13/Synology-NAS-monitoring#4]
As title. I provided the docker-compose file for you on Reddit, off the top of my head. Having run it, I realised that `- 5144:514` needs  to actually be `- 5144:514/udp` to function. Once this change is made, logging now works. Sorry for the mistake.

**Comment by alhazmy13** [comment]
Fixed with https://github.com/alhazmy13/Synology-NAS-monitoring/pull/5
Thanks @RainmakerRaw
