### ISSUE TITLE
Some Data are missing

### ISSUE THREAD

**Issue by oschmidteu** [alhazmy13/Synology-NAS-monitoring#7]
Hey thanks for the packeg.
Was very easy to set it up and looks very good but a few datas are missing:
![image](https://user-images.githubusercontent.com/13415307/124239190-b9a20300-db19-11eb-80ca-372122460186.png)
Not sure if this ist due to DSM 7 or because i use the NVME SSDs as a second volume.

Any idea?

**Comment by angadsingh** [comment]
+1 same here.. i think its because of a version issue. i can see that the MIBs have changed:
```
snmpwalk -c public -v 2c 127.0.0.1 .1.3.6.1.4.1.6574.6
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.1 = INTEGER: 1
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.2 = INTEGER: 2
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.3 = INTEGER: 3
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.4 = INTEGER: 4
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.5 = INTEGER: 5
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.6 = INTEGER: 6
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.7 = INTEGER: 7
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.8 = INTEGER: 8
SYNOLOGY-SERVICES-MIB::serviceInfoIndex.9 = INTEGER: 9
SYNOLOGY-SERVICES-MIB::serviceName.1 = STRING: "CIFS"
SYNOLOGY-SERVICES-MIB::serviceName.2 = STRING: "AFP"
SYNOLOGY-SERVICES-MIB::serviceName.3 = STRING: "NFS"
SYNOLOGY-SERVICES-MIB::serviceName.4 = STRING: "FTP"
SYNOLOGY-SERVICES-MIB::serviceName.5 = STRING: "SFTP"
SYNOLOGY-SERVICES-MIB::serviceName.6 = STRING: "HTTP/HTTPS"
SYNOLOGY-SERVICES-MIB::serviceName.7 = STRING: "TELNET"
SYNOLOGY-SERVICES-MIB::serviceName.8 = STRING: "SSH"
SYNOLOGY-SERVICES-MIB::serviceName.9 = STRING: "OTHER"
SYNOLOGY-SERVICES-MIB::serviceUsers.1 = INTEGER: 0
SYNOLOGY-SERVICES-MIB::serviceUsers.2 = INTEGER: 2
SYNOLOGY-SERVICES-MIB::serviceUsers.3 = INTEGER: 0
SYNOLOGY-SERVICES-MIB::serviceUsers.4 = INTEGER: 0
SYNOLOGY-SERVICES-MIB::serviceUsers.5 = INTEGER: 0
SYNOLOGY-SERVICES-MIB::serviceUsers.6 = INTEGER: 1
SYNOLOGY-SERVICES-MIB::serviceUsers.7 = INTEGER: 0
SYNOLOGY-SERVICES-MIB::serviceUsers.8 = INTEGER: 2
SYNOLOGY-SERVICES-MIB::serviceUsers.9 = INTEGER: 0
```

**Comment by nevusZ** [comment]
+1
same here
have you solved it somehow?

**Comment by rotanon** [comment]
@nevusZ it appears the IP address of the synology server is hardcoded in the telegraf input file

**Comment by vnl** [comment]
Same issue, @rotanon what is the hardcoding causing?

**Comment by EliasADN** [comment]
> Hey thanks for the packeg. Was very easy to set it up and looks very good but a few datas are missing: ![image](https://user-images.githubusercontent.com/13415307/124239190-b9a20300-db19-11eb-80ca-372122460186.png) Not sure if this ist due to DSM 7 or because i use the NVME SSDs as a second volume.
> 
> Any idea?

Check the logs of Docker, if you have something about "INFO exited: snmpwalk (exit status 1; not expected)" you need configure a rule in your synology firewall,  port 161 udp from the docker network

**Comment by neomelb** [comment]
> > Hey thanks for the packeg. Was very easy to set it up and looks very good but a few datas are missing: ![image](https://user-images.githubusercontent.com/13415307/124239190-b9a20300-db19-11eb-80ca-372122460186.png) Not sure if this ist due to DSM 7 or because i use the NVME SSDs as a second volume.
> > Any idea?
> 
> Check the logs of Docker, if you have something about "INFO exited: snmpwalk (exit status 1; not expected)" you need configure a rule in your synology firewall, port 161 udp from the docker network

Thanks!
I've also experienced the same issue and looking for a resolution for a few days.
Firewall was not enabled when the issue occurred.
I have enabled the Firewall and manually added a rule to open up port UDP161, it fixed the issue!

**Comment by alhazmy13** [comment]
Thanks @neomelb for sharing this
@oschmidteu Can you please confirm if adding UDP/161 rule to the Firewall fixed your issue?

**Comment by mase1981** [comment]
I am having this same issue since recent update (today), adding the firewall rule to test. will report back. 
Edit: Adding 161 UDP allow from Docker network 172.12.0.0/16 did not solve this issue. However, i have disabled firewall and it immediately started working. Debugging to identify where is the missing rule. 

Edit: 
Add new rule: 
Select from a built in applications
SNMP Services
Source: 172.12.0.0 / subnet: 255.255.0.0
Add the rule
move the rule from the bottom to be above the deny/deny all
disable and re-enable the firewall for it to take affect
Should fix the issue.

**Comment by alhazmy13** [comment]
Thanks for the confirmation @mase1981
